### ISSUE TITLE
gradient_n_pal to interpolate in the CIELab color space

### ISSUE THREAD

**Issue by stphnlyd** [stphnlyd/perl5-Chart-GGPlot#12]
R's scales::gradient_n_pal() uses the Lab space. Now in Chart::GGPlot we use the RGB space. The two are somewhat different. This would affect the result scale_color/fill_gradient(). 

https://metacpan.org/pod/Graphics::ColorObject has functions for converting between RGB and Lab space. But this project is not maintained after 2005 and cannot even install. We probabaly can test it and if it's good we can port only what's necessary to our code.

**Comment by mohawk2** [comment]
https://metacpan.org/pod/PDL::Transform::Color#t_cielab-or-t_lab converts RGB <-> Lab space.

**Comment by stphnlyd** [comment]
pending on https://github.com/PDLPorters/PDL-Transform-Color/issues/5

**Comment by stphnlyd** [comment]
pending https://github.com/PDLPorters/PDL-Transform-Color/issues/6

**Comment by mohawk2** [comment]
P:T:Color has been fairly thoroughly updated, and now uses in many places PDL::Graphics::ColorSpace, which is itself a PDL port of Graphics::ColorObject.

**Comment by stphnlyd** [comment]
Using PDL::Graphics::ColorSpace and released as 0.002002
