### ISSUE TITLE
Error installation " Failed test:  14  Non-zero exit status: 1".

### ISSUE THREAD

**Issue by Bortechino** [stphnlyd/perl5-Chart-GGPlot#6]
System information:
System:
  Host: mx Kernel: 4.19.0-1-amd64 x86_64 bits: 64 compiler: gcc v: 6.3.0 
  Desktop: Xfce 4.12.3 Distro: MX-18.1_x64 Continuum Feb 9  2019 
  base: Debian GNU/Linux 9 (stretch) 
Machine:
  Type: Portable System: Dell product: Inspiron 5545 v: A02 serial: <filter> 
  Mobo: Dell model: 0D5K2H v: A00 serial: <filter> UEFI [Legacy]: Dell 
  v: A02 date: 06/17/2014 
__________
Cpan report:
[cpan Chart-GGPlot.txt](https://github.com/stphnlyd/perl5-Chart-GGPlot/files/3025343/cpan.Chart-GGPlot.txt)

**Comment by stphnlyd** [comment]
@Bortechino 

The test failure is about the dollar() utility function which can be used for formatting axis tick labels, for example see https://github.com/stphnlyd/perl5-Chart-GGPlot/blob/master/examples/scale_continuous_02_02.pl and the y-axis of https://github.com/stphnlyd/perl5-Chart-GGPlot/blob/master/examples/scale_continuous_02_02.png

Presently my implementation uses [Number::Format's format_price method](https://metacpan.org/pod/Number::Format#format_price($number,-$precision,-$symbol)), which would use some of your locale settings. 

If you don't have to use this dollar() function and would just like to try out Chart::GGPlot, you can just ignore this test failure and force install it. I will try to figure out how to fix it on my side, and have the fix in my next release.

**Comment by stphnlyd** [comment]
@Bortechino I released to CPAN new Chart::GGPlot the other day. I guess this issue should have been fixed. Could you confirm that?

**Comment by Bortechino** [comment]
All right!! Many, many, many thanks!! 
Chart::GGPlot's been installed without any issues!!
